export const categories = [
  {
    id: "tech",
    name: "Tignoolajiyada",
    nameEn: "Technology",
    icon: "💻",
    gradient: "from-primary-600 to-accent-600",
    description:
      "Ka wada hadal tignoolajiyada cusub, software, iyo xirfadaha IT.",
    banner: "Casriyeenta aqoonta tignoolajiyada Soomaaliyeed.",
    members: 12850,
    moderator: "Ayaan T.",
  },
  {
    id: "business",
    name: "Ganacsiga",
    nameEn: "Business",
    icon: "💼",
    gradient: "from-accent-600 to-cta-600",
    description: "Ganacsi, suuq-geyn, iyo kobaca ganacsiga yar iyo weyn.",
    banner: "Horumari fikirka ganacsi ee bulshada.",
    members: 9640,
    moderator: "Hassan A.",
  },
  {
    id: "education",
    name: "Waxbarashada",
    nameEn: "Education",
    icon: "📚",
    gradient: "from-primary-700 to-primary-500",
    description: "Talada waxbarasho, jaamacado, iyo barnaamijyo tababar.",
    banner: "Wadada aqoonta iyo waxbarashada joogtada ah.",
    members: 14320,
    moderator: "Khadra M.",
  },
  {
    id: "health",
    name: "Caafimaadka",
    nameEn: "Health",
    icon: "🏥",
    gradient: "from-cta-600 to-accent-600",
    description: "Talo caafimaad, nafaqo, iyo fayo-qabka bulshada.",
    banner: "Bulsho caafimaad qabta, bulsho horumarta.",
    members: 7820,
    moderator: "Dr. Saadia",
  },
  {
    id: "culture",
    name: "Dhaqanka",
    nameEn: "Culture",
    icon: "🎭",
    gradient: "from-cta-500 to-cta-600",
    description: "Dhaqanka, suugaanta, iyo hidaha Soomaaliyeed.",
    banner: "Dhis aqoonsi iyo wadaag hidde.",
    members: 6210,
    moderator: "Mustafe H.",
  },
  {
    id: "general",
    name: "Guud",
    nameEn: "General",
    icon: "🌟",
    gradient: "from-primary-600 to-primary-500",
    description: "Dood guud iyo su'aalo aan ku xaddidnayn qayb gaar ah.",
    banner: "Wadahadal guud oo furan.",
    members: 20150,
    moderator: "Admin",
  },
];
